### PR TITLE
chore: bump k8s packages to 1.29

### PR DESCRIPTION
**Pull request by realshuting**
Hi 👋

We are from Kyverno and currently working on Kubernetes Pod Security admission integration (https://github.com/kyverno/kyverno/pull/7412). We were trying to upgrade to latest 1.29 Kubernetes versions and found this package is still on k8s tag 0.28.1.

This PR bumps the k8s packages to use latest 1.29.

### CODE REVIEW

**Comment by alexzielenski** [comment]
Preferring not to depend on the alpha tags. 1.29 releases tomorrow I believe. Would it be possible to use the stable tags then?

**Comment by realshuting** [comment]
> Preferring not to depend on the alpha tags. 1.29 releases tomorrow I believe. Would it be possible to use the stable tags then?

Sure, will update to the stable version once it's available.

**Comment by eddycharly** [comment]
@realshuting stable packages are now available

**Comment by realshuting** [comment]
> @realshuting stable packages are now available

Bumped to the stable version!

**Comment by alexzielenski** [comment]
CI doesnt like the go.mod version. Does that work locally for you?

**Comment by realshuting** [comment]
> CI doesnt like the go.mod version. Does that work locally for you?

Updated to Go 1.23.

**Pull request merged**
