### PR TITLE
feat: add custom strfmt.Registry support

### PR DESCRIPTION
**Pull request by eddycharly**
This PR adds custom `strfmt.Registry` support.

Format `byte` does not allow empty strings (see comes from https://github.com/asaskevich/govalidator/blob/a9d515a09cc289c60d55064edec5ef189859f172/patterns.go#L27).

This makes the secret below invalid:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: secret
data:
  key: ''
```

Now, one could supply it's own registry like this to workaround the problem:
```golang
	registry := strfmt.NewFormats()
	b64 := strfmt.Base64([]byte(nil))
	registry.Add("byte", &b64, func(s string) bool {
		if len(s) == 0 {
			return true
		}
		return govalidator.IsBase64(s)
	})
```

### CODE REVIEW

**Comment by alexzielenski** [comment]
This is an interesting bug. Native k8s types do not undergo schema validation so the empty string was allowed. CRDs not he other hand do, and use `strfmt.Default`. 

I just tested this by making a CRD with a field with `type: string` and `format: byte` like `Secret`. K8s apiserver rejected it with:
```
* bytesField: Invalid value: "": bytesField in body must be of type byte: ""
```

So to fix this for native types causes CRD validation to be incorrect (unless we hardcoded some logic to decide which strfmt to use depending on the GVK, but thats not nice).

I wonder if this is a bug that should be fixed upstream, so that in k8s CRDs are allowed to have empty `byte` values

**Comment by eddycharly** [comment]
> I wonder if this is a bug that should be fixed upstream, so that in k8s CRDs are allowed to have empty byte values

I wondered the same. Dunno maybe it was done intentionally.

**Comment by eddycharly** [comment]
I thought it was acceptable to allow providing a custom registry, WDYT ?

**Comment by eddycharly** [comment]
Or maybe a registry provider that can return a registry depending on the resource being validated ?

**Comment by alexzielenski** [comment]
> I thought it was acceptable to allow providing a custom registry, WDYT ?

I dont think so, since the custom registry will either be wrong for native types, or wrong for CRDs. It would never be correct for both unless you provided a registry depending on the type. 

> Or maybe a registry provider that can return a registry depending on the resource being validated ?

Yeah, In the worst case scenario we can use the registry conditionally for native types, but I'd like to avoid that if we can. Unfortunately patching upstream seems the solution I can think of.

**Comment by eddycharly** [comment]
> Unfortunately patching upstream seems the solution I can think of.

You mean changing the format validator for `byte` upstream ?

**Comment by eddycharly** [comment]
Closing, became useless with recent changes.

**Pull request closed without merging**
