### PR TITLE
fix: remove dead code

### PR DESCRIPTION
**Pull request by eddycharly**
This PR removes a bit of dead code.

### CODE REVIEW

**Comment by apelisse** [comment]
it looks like there are more things that you can remove

**Comment by eddycharly** [comment]
> it looks like there are more things that you can remove

yeah but as it's WIP I don't want to remove something @alexzielenski plans to use soon.

**Comment by alexzielenski** [comment]
`celValidator` can be removed. It was from an older implementation

**Comment by apelisse** [comment]
/lgtm
/approve

Manually merged so I could use the "rebase and merge" button?

**Pull request merged**
