### PR TITLE
update to go 1.21

### PR DESCRIPTION
**Pull request by kannon92**
#### What type of PR is this?
/kind feature

#### What this PR does / why we need it:
Update to go 1.21. Kubernetes releases are at 1.21 and many projects are slowly updating their mains to reflect 1.22.
#### Which issue(s) this PR fixes:

Fixes #

#### Special notes for your reviewer:
I think we should upgrade to 1.22 soon as 1.30 is set to 1.22 but I think a single version bump is good for a PR.
#### Does this PR introduce a user-facing change?

```release-note
support golang 1.21
```

#### Additional documentation e.g., KEPs (Kubernetes Enhancement Proposals), usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by eddycharly** [comment]
This will force users to switch to 1.22 right ?

**Comment by kannon92** [comment]
> This will force users to switch to 1.22 right ?

I think they could use 1.21. 

I may need to bump to 1.21 first. The CI is failing because the commit we use for github actions doesn't support 1.22 at the moment.

**Comment by kannon92** [comment]
Downgraded from 1.22 to 1.21. This is green now.

**Pull request merged**
