### PR TITLE
chore: fix unit tests

### PR DESCRIPTION
**Pull request by eddycharly**
This PR fixes unit tests.

One thing though, creating a pod with a container that has no image is valid.
@alexzielenski  It looks like we are patching the schema to make image a required field ?

### CODE REVIEW

**Comment by eddycharly** [comment]
@alexzielenski no problem to close it.

Still, creating pods with containers having no image is valid, we should at least make the patching optional.

**Comment by alexzielenski** [comment]
> Still, creating pods with containers having no image is valid, we should at least make the patching optional.

Do you have a source/example of this? When I try to apply the case to my cluster I get the expected error, and in the source for Container validation there is logic to throw this error:

https://github.com/kubernetes/kubernetes/blob/3f8c4794eadf8aadd8a5bcb0b875bf0af5c2020b/pkg/apis/core/validation/validation.go#L3220-L3222

```console
$ kubectl apply -f testcases/manifests/error_missing_image.yaml
The Pod "nginx-pod" is invalid: spec.containers[0].image: Required value

$ kubectl apply -f testcases/manifests/error_missing_image.yaml --server-side=true
The Pod "nginx-pod" is invalid: spec.containers[0].image: Required value
```

**Comment by alexzielenski** [comment]
/close

in favor of #21

**Comment by eddycharly** [comment]
Hmmm maybe it’s just on openshift ?
It’s used with image streams iirc

**Pull request closed without merging**
