### PR TITLE
added pr template

### LINKED ISSUE #87: add a pr template
currently there is no pr template please add it

### PR DESCRIPTION
**Pull request by swastik959**
added pr template

closes #87

### CODE REVIEW

**Comment by swastik959** [comment]
hi @alexzielenski can you please review this pr

**Review by alexzielenski — CHANGES_REQUESTED** [review]
I think for consistency the kubernetes/kubernetes template is fine
https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Comment by swastik959** [comment]
@alexzielenski I have done the relevant changes please review it now

**Comment by apelisse** [comment]
I agree with Alex that this looks better.

**Comment by swastik959** [comment]
@alexzielenski any update on this pr

**Pull request merged**
