### PR TITLE
fix: invalid go version

### PR DESCRIPTION
**Pull request by realshuting**
Hi @alexzielenski - this PR is to fix the Go version to match the expected [format](https://github.com/kubernetes-sigs/kubectl-validate/actions/runs/7208892806/job/19648948870#step:3:22), the latest release is 1.21.5, not 1.23.x.

I misunderstood the error message :(
>  level=error msg="Running error: context loading failed: failed to load packages: failed to load with go/packages: err: exit status 1: stderr: go: errors parsing go.mod:\n/home/runner/work/kubectl-validate/kubectl-validate/go.mod:3: invalid go version '1.21.4': must match format 1.23\n"

Related: https://github.com/kubernetes-sigs/kubectl-validate/pull/81.

### CODE REVIEW

**Comment by realshuting** [comment]
Looks like it requires 1.20, let me downgrade it.

>Run go mod tidy && git diff --exit-code
go: go.mod file indicates go 1.21, but maximum version supported by tidy is 1.20
Error: Process completed with exit code 1.

**Comment by realshuting** [comment]
The same test failed when I tested with 1.21 in go.mod. Something has changed in the underlying library 🤔
```
Error: validation failed
--- FAIL: TestValidationErrorsIndividually (0.66s)
    --- FAIL: TestValidationErrorsIndividually/error_cel_basic (0.0[7](https://github.com/kubernetes-sigs/kubectl-validate/actions/runs/7382489927/job/20095015105#step:7:8)s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x177ec91]

goroutine 114 [running]:
testing.tRunner.func1.2({0x1c1c300, 0x5a457c0})
	/opt/hostedtoolcache/go/1.20.12/x64/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.20.12/x64/src/testing/testing.go:1529 +0x39f
panic({0x1c1c300, 0x5a457c0})
	/opt/hostedtoolcache/go/1.20.12/x64/src/runtime/panic.go:[8](https://github.com/kubernetes-sigs/kubectl-validate/actions/runs/7382489927/job/20095015105#step:7:9)84 +0x213
k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel.validator(0xc000ac8c60, 0x1, 0x0, 0xc000[10](https://github.com/kubernetes-sigs/kubectl-validate/actions/runs/7382489927/job/20095015105#step:7:11)0000?)
	/home/runner/work/kubectl-validate/kubectl-validate/vendor/k8s.io/apiextensions-apiserver/pkg/apiserver/schema/cel/validation.go:106 +0x2b1
```

**Comment by alexzielenski** [comment]
/lgtm
/approve

the test failure was introduced in the PR bumping the change. I did not notice this bit: 

https://github.com/kubernetes-sigs/kubectl-validate/blob/89b8a1016e43dd75c94a91b09a2014730498f9fe/pkg/validator/validator.go#L123-L129

Approving this so we can run the CI again. I have a followup PR to fix the test

**Comment by realshuting** [comment]
> /lgtm /approve
> 
> the test failure was introduced in the PR bumping the change. I did not notice this bit:
> 
> https://github.com/kubernetes-sigs/kubectl-validate/blob/89b8a1016e43dd75c94a91b09a2014730498f9fe/pkg/validator/validator.go#L123-L129
> 
> Approving this so we can run the CI again. I have a followup PR to fix the test

Thank you @alexzielenski !

**Pull request merged**
