### PR TITLE
Add required job

### PR DESCRIPTION
**Pull request by apelisse**
Let's see if this works. We shouldn't be able to merge until all the required jobs have passed.

### CODE REVIEW

**Comment by apelisse** [comment]
OK, it doesn't work, we need all the jobs in the same file, fine.

**Comment by eddycharly** [comment]
> OK, it doesn't work, we need all the jobs in the same file, fine.

What do you mean ?
Workflow files and required status checks are not coupled (you can configure required jobs in branch protections).

**Comment by alexzielenski** [comment]
Inclined to agree with @eddycharly's approach of adding all the required jobs into branch protections. It looks like you or someone already added "required" to branch protections, why not all of its contained jobs instead?

**Comment by apelisse** [comment]
Job protection is set by a prow job configured in a sepate repo (here: https://github.com/apelisse/test-infra/blob/master/config/prow/config.yaml), which means any change to this requires a pull-request in another repo (e.g. https://github.com/kubernetes/test-infra/pull/29487). That's frustrating because we need to get approval/lgtm from someone else that doesn't know anything about our repo.

Having a static "required" job here and then locally defining which jobs are required solves this problem and works fine.

**Comment by apelisse** [comment]
Something is wrong for sure.

**Pull request merged**
