### PR TITLE
Refactor validator factory

### PR DESCRIPTION
**Pull request by alexzielenski**
Improves ergonomics of the validator package quite a bit:

1. Renames `validatorfactory` to `validator`
2. Changes workflow with the factory to be:
    ```go
    myValidator := validator.New(myOpenAPIClient)
    _, parsedDoc, error := myValidator.Parse(myDocument)
    error := myValidator.Validate(parsedDoc)
    ```
    from
    ```go
	var metadata metav1.TypeMeta
	gvk := metadata.GetObjectKind().GroupVersionKind()
	factory, err := New(tt.client)
	validator, err := factory.ValidatorsForGVK(gvk)
	decoder, err := validator.Decoder(gvk)
	info, ok := runtime.SerializerInfoForMediaType(decoder.SupportedMediaTypes(), runtime.ContentTypeYAML)
	var untyped unstructured.Unstructured
	_, _, err = decoder.DecoderToVersion(info.StrictSerializer, gvk.GroupVersion()).Decode(document, &gvk, &untyped)
	ss, err := validators.StructuralSchema()
	strat := customresource.NewStrategy(validators.ObjectTyper(gvk), validator.IsNamespaced, gvk, validators.SchemaValidator(), nil, map[string]*apiextensionsschema.Structural{
		gvk.Version: ss,
	}, nil, nil)

	rest.FillObjectMetaSystemFields(&untyped)
	err := rest.BeforeCreate(strat, request.WithNamespace(context.TODO(), untyped.GetNamespace()), &untyped)
    ```
3. Refactors `removeRefs` in terms of the schema visitor

### CODE REVIEW

**Comment by alexzielenski** [comment]
/cc @eddycharly 
since kyverno uses the tool as a library I you may like to be aware of these changes

**Comment by eddycharly** [comment]
Thanks @alexzielenski why is `validator.go` in testdata folder ?

**Comment by alexzielenski** [comment]
> Thanks @alexzielenski why is `validator.go` in testdata folder ?

It isnt, GitHub's file tree view just does not indent children enough

**Comment by eddycharly** [comment]
🙈

**Pull request merged**
