### PR TITLE
chore: add ci workflow

### PR DESCRIPTION
**Pull request by eddycharly**
This PR adds a `ci` workflow to build and check code format/go.mod

### CODE REVIEW

**Comment by alexzielenski** [comment]
Should this workflow also check these?:

1. `go vet`
2. `go fmt` has no differences
3. [`staticcheck`](https://staticcheck.io/docs/)

I assume there would be a separate workflow that runs the tests. Is there guidance about when to split the workflow into separate jobs vs to just run all the commands in a single job?

**Comment by apelisse** [comment]
There is gofmt, not sure how staticcheck and go vet are different from the golangci-lint

**Comment by eddycharly** [comment]
Yeah, staticcheck and go vet are part of golangci-lint (go fmt too though).

**Comment by eddycharly** [comment]
I'll add a test workflow tomorrow, i think i'll need to fix the tests at the same time.

**Comment by alexzielenski** [comment]
Im working on fixing tests now :)

**Pull request merged**
